#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
"""
Mime-type module.

A list of mime-types and their file extensions.
"""


MIME_TYPES = [
    ["application/epub+zip", ".epub"],
    ["application/excel", ".xls"],
    ["application/gnutar", ".tgz"],
    ["application/gzip", ".gz"],
    ["application/javascript", ".js"],
    ["application/json", ".json"],
    ["application/ld+json", ".jsonld"],
    ["application/mspowerpoint", ".ppt"],
    ["application/msword", ".doc"],
    ["application/octet-stream", ".bin"],
    ["application/ogg", ".ogx"],
    ["application/pdf", ".pdf"],
    ["application/php", ".php"],
    ["application/plain", ".txt"],
    ["application/powerpoint", ".ppt"],
    ["application/rtf", ".rtf"],
    ["application/vnd.amazon.ebook", ".azw"],
    ["application/vnd.apple.installer+xml", ".mpkg"],
    ["application/vnd.ms-excel", ".xls"],
    ["application/vnd.ms-powerpoint", ".ppt"],
    ["application/vnd.oasis.opendocument.presentation", ".odp"],
    ["application/vnd.oasis.opendocument.spreadsheet", ".ods"],
    ["application/vnd.oasis.opendocument.text", ".odt"],
    ["application/vnd.openxmlformats-officedocument.presentationml.presentation",
     ".pptx"],
    ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
     ".xlsx"],
    ["application/vnd.openxmlformats-officedocument.wordprocessingml.document",
     ".docx"],
    ["application/vnd.rar", ".rar"],
    ["application/vnd.visio", ".vsd"],
    ["application/x-7z-compressed", ".7z"],
    ["application/x-bsh", ".sh"],
    ["application/x-bzip", ".bz"],
    ["application/x-bzip2", ".bz2"],
    ["application/x-compressed", ".zip"],
    ["application/x-excel", ".xls"],
    ["application/x-gzip", ".gz"],
    ["application/x-javascript", ".js"],
    ["application/x-msexcel", ".xls"],
    ["application/x-mspowerpoint", ".ppt"],
    ["application/x-sh", ".sh"],
    ["application/x-shockwave-flash", ".swf"],
    ["application/x-tar", ".tar"],
    ["application/x-visio", ".vsd"],
    ["application/x-zip-compressed", ".zip"],
    ["application/xhtml+xml", ".xhtml"],
    ["application/xml", ".xml"],
    ["application/zip", ".zip"],
    ["audio/aac", ".aac"],
    ["audio/aiff", ".aif"],
    ["audio/midi", ".midi"],
    ["audio/mp3", ".mp3"],
    ["audio/mp4", ".mp4"],
    ["audio/mpeg", ".mp3"],
    ["audio/ogg", ".oga"],
    ["audio/opus", ".opus"],
    ["audio/wav", ".wav"],
    ["audio/webm", ".weba"],
    ["audio/x-aiff", ".aif"],
    ["audio/x-midi", ".midi"],
    ["audio/x-mpeg", ".mp2"],
    ["audio/x-mpeg-3", ".mp3"],
    ["audio/x-wav", ".wav"],
    ["binary/octet-stream", ".png"],
    ["font/otf", ".otf"],
    ["font/ttf", ".ttf"],
    ["font/woff", ".woff"],
    ["font/woff2", ".woff2"],
    ["image/bmp", ".bmp"],
    ["image/gif", ".gif"],
    ["image/jpeg", ".jpg"],
    ["image/pjpeg", ".jpg"],
    ["image/png", ".png"],
    ["image/svg+xml", ".svg"],
    ["image/tiff", ".tiff"],
    ["image/vnd.microsoft.icon", ".ico"],
    ["image/webp", ".webp"],
    ["image/x-icon", ".ico"],
    ["image/x-tiff", ".tiff"],
    ["image/x-windows-bmp", ".bmp"],
    ["message/rfc822", ".mht"],
    ["multipart/x-gzip", ".gzip"],
    ["multipart/x-zip", ".zip"],
    ["text/calendar", ".ics"],
    ["text/css", ".css"],
    ["text/csv", ".csv"],
    ["text/html", ".html"],
    ["text/javascript", ".js"],
    ["text/plain", ".txt"],
    ["text/richtext", ".rtf"],
    ["text/tab-separated-values", ".tsv"],
    ["text/x-vcalendar", ".vcs"],
    ["text/xml", ".xml"],
    ["video/avi", ".avi"],
    ["video/mp4", ".mp4"],
    ["video/mpeg", ".mpeg"],
    ["video/mpv", ".mpv"],
    ["video/msvideo", ".avi"],
    ["video/ogg", ".ogv"],
    ["video/quicktime", ".mov"],
    ["video/webm", ".webm"],
    ["video/x-mpeg", ".mpg"],
    ["video/x-msvideo", ".avi"],
    ["www/mime", ".mime"],
    ["x-music/x-midi", ".midi"]
]
